name: Auto Select & Upload CF IP

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:        # 支持手动触发

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 curl

      - name: Run IP Selector
        run: python3 ip_selector.py

      - name: Upload to API
        run: python3 upload_to_api.py
