name: Auto Select & Upload CF IP

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:        # 支持手动触发

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 curl

      - name: Generate IP list
        run: |
          echo "1.1.1.1" > ip.txt
          echo "1.0.0.1" >> ip.txt
          echo "104.16.132.229" >> ip.txt
          echo "104.17.175.85" >> ip.txt
          echo "162.159.192.1" >> ip.txt

      - name: Upload ip.txt to GitHub repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python3 upload_to_api.py
